version: '3.8'

services:
  web:
    build: .
    container_name: django_faq
    command: gunicorn --bind 0.0.0.0:8000 faq_project.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DEBUG=True

  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
