# Generated by Django 5.1.5 on 2025-02-01 12:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Question in English')),
                ('answer', ckeditor.fields.RichTextField(help_text='Answer in English (WYSIWYG enabled)')),
                ('question_hi', models.TextField(blank=True, help_text='Question in Hindi', null=True)),
                ('question_bn', models.TextField(blank=True, help_text='Question in Bengali', null=True)),
                ('answer_hi', ckeditor.fields.RichTextField(blank=True, help_text='Answer in Hindi', null=True)),
                ('answer_bn', ckeditor.fields.RichTextField(blank=True, help_text='Answer in Bengali', null=True)),
            ],
        ),
    ]
